[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
exoduze_prediction_market = "HktRmDZBsEgpHCuEkzGMsy2RQdsWzMzyNxf7hHHvFkMU"

[programs.devnet]
exoduze_prediction_market = "HcK2u8Ko7L8ZXPRSUAC7ZiDYyT9LuRS383KChtzhkBkd"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha --timeout 1000000 tests/**/*.js"
